%% DAC vs pe
%% recalculate coeffs
%% redo with 2 methods:
%% 1) use 2 and 5 pe levels
%% 2) use mean of A_ima A_ph and B_ima B_ph
%% make mixed fig
%%
%% 1)  use 2 and 5 pe levels
%%%%% get values for 2 pe
% using pestepImadac (quadrant, gains, pelev starting at 2)
% on veut trouver la pente et intercept de dactab = A pe + B
%% a 2 pe on a dac2= 2A +B ; a 5pe on a dac5 = 5A + B
%% (2)-(1) gives A =(1/3) * (dac5-dac2) et B = dac2-(2/3)*(dac5-dac2) = (5/3)*dac2 -(2/3)*dac5
gaintaballg=[40 60];
An=zeros(4, numel(gaintaballg));
Bn=zeros(4, numel(gaintaballg));
cpsfinalallpesfigcell=cell(numel(gaintaballg),4);
cpsfinalallfitfigcell=cell(numel(gaintaballg),4);
for quad=1:4
    for ig=1: numel(gaintaballg)
        dac2=pestepImadac(quad,ig,1); %start at 2pe
        dac5=pestepPHdac(quad,ig,2); %start at 4pe
        An(quad,ig) = (1/gaintaballg(ig)) * (1/3) * (dac5-dac2);
        Bn(quad,ig) =  (5/3)*dac2 -(2/3)*dac5;
    end
end
%%final res: moyenne over gains
An2=mean(An,2);
Bn2=mean(Bn,2);


%% 2) use mean of A_ima A_ph and B_ima B_ph

%% for ima:
%coeffsallg(1,2)/coeffsallg(1,1))
load(([getuserdir '\panoseti\Calibrations\' 'CalibrationDB.mat']))
[ig,indexquabosn]=ismember(['QuaboSN'] ,quaboconfig);
inddetrow=find(quaboDETtable(:,1)==str2num(cell2mat(quaboconfig(indexquabosn,3))));

AAima=zeros(1,4);
BBima=zeros(1,4);
for quad=1:4
    AAima(quad)=quaboDETtable(inddetrow,6+quad);
    BBima(quad)=quaboDETtable(inddetrow,10+quad);
end


%%needs to be calculated for PH mode between 4 and 5 pe
%% a 4pe pe on a dac4= 4A +B ; a 5pe on a dac5 = 5A + B
%% (2)-(1) gives A = (dac5-dac4) et B = (5)*dac4 -(4)*dac5
%%
AAph=zeros(4, numel(gaintaballg));
BBph=zeros(4, numel(gaintaballg));
for quad=1:4
    for ig=1: numel(gaintaballg)
        dac4=pestepPHdac(quad,ig,1); %start at 4pe
        dac5=pestepPHdac(quad,ig,2); %start at 4pe
        AAph(quad,ig) = (1/gaintaballg(ig)) *(dac5-dac4);
        BBph(quad,ig) =  (5)*dac4 -(4)*dac5;
    end
end
AAph2=mean(AAph,2);
BBph2=mean(BBph,2);

%%final averaging between AAs and BBs of Ima and PH modes
AAimaph=zeros(1,4);
BBimaph=zeros(1,4);
for quad=1:4
    AAimaph(quad)=mean([AAph2(quad) AAima(quad)]);
    BBimaph(quad)=mean([BBph2(quad) BBima(quad)]);
end

%% FINAL A&B coeffs
Af=mean(cat(1,An2', AAimaph),1);
Bf=mean(cat(1,Bn2', BBimaph),1);


disp('****** coeffs A, B (dactab = A g pe + B) *************')
disp('from 2-3 pe Ima:')
disp(['A0:' num2str(quaboDETtable(inddetrow,7)) ...
    ' A1:' num2str(quaboDETtable(inddetrow,8)) ...
    ' A2:' num2str(quaboDETtable(inddetrow,9)) ...
    ' A3:' num2str(quaboDETtable(inddetrow,10))])
disp('from 2-5 pe Ima/PH:')
disp(['A0:' num2str(An2(1)) ...
    ' A1:' num2str(An2(2)) ...
    ' A2:' num2str(An2(3)) ...
    ' A3:' num2str(An2(4))])
disp('from  mean of A_ima A_ph:')
disp(['A0:' num2str(AAimaph(1)) ...
    ' A1:' num2str(AAimaph(2)) ...
    ' A2:' num2str(AAimaph(3)) ...
    ' A3:' num2str(AAimaph(4))])
disp('Afinal (mean last 2 methods):')
disp(['A0:' num2str(Af(1)) ...
    ' A1:' num2str(Af(2)) ...
    ' A2:' num2str(Af(3)) ...
    ' A3:' num2str(Af(4))])
disp('from 2-3 pe Ima:')
disp(['B0:' num2str(quaboDETtable(inddetrow,11)) ...
    ' B1:' num2str(quaboDETtable(inddetrow,12)) ...
    ' B2:' num2str(quaboDETtable(inddetrow,13)) ...
    ' B3:' num2str(quaboDETtable(inddetrow,14))])
disp('from 2-5 pe Ima/PH:')
disp(['B0:' num2str(Bn2(1)) ...
    ' B1:' num2str(Bn2(2)) ...
    ' B2:' num2str(Bn2(3)) ...
    ' B3:' num2str(Bn2(4))])
disp('from  mean of B_ima B_ph:')
disp(['B0:' num2str(BBimaph(1)) ...
    ' B1:' num2str(BBimaph(2)) ...
    ' B2:' num2str(BBimaph(3)) ...
    ' B3:' num2str(BBimaph(4))])
disp('Bfinal (mean last 2 methods):')
disp(['B0:' num2str(Bf(1)) ...
    ' B1:' num2str(Bf(2)) ...
    ' B2:' num2str(Bf(3)) ...
    ' B3:' num2str(Bf(4))])
%%sauvegrade new calib file
%%produce report products
%%add DAC vs pe coeffs table
if makereport==1
        import mlreportgen.report.*
    import mlreportgen.dom.*
    sec5 = Section;
    sec5.Title = ['DAC = A g pe# + B'];
     add(sec5,Paragraph(['(A g) and B coefficients are deduced from measurements in both imaging and PH modes using dark acquisitions. Indeed, 2,3,4-pe steps can be quickly detected with dark cps in imaging mode' ...
         ' whereas 4,5,6-pe steps can be quickly detected from cps curves in PH mode. Therefore, we can deduce A and B coefficients ' ...
         'from different methods considering different pe steps to deduce them.']));
      add(sec5,Paragraph(['The following table gives Ag, A, B coefficients for Quadrants#0,1,2,3 where g is the initial gain.']));
   tableStyle = ...
    { ...
    Width("100%"), ...
    Border("solid"), ...
    RowSep("solid"), ...
    ColSep("solid") ...
    };

tableEntriesStyle = ...
    { ...
    HAlign("center"), ...
    VAlign("middle") ...
    };

headerRowStyle = ...
    { ...
    InnerMargin("2pt","2pt","2pt","2pt"), ...
    BackgroundColor("gray"), ...
    Bold(true) ...
    };
grps(1) = TableColSpecGroup;
grps(1).Span = 11;

specs3(1) = TableColSpec;
specs3(1).Span = 1;
specs3(1).Style = {Width("3%")};

specs3(2) = TableColSpec;
specs3(2).Span = 1;
specs3(2).Style = {Width("15%")};

specs3(3) = TableColSpec;
specs3(3).Span = 1;
specs3(3).Style = {Width("9%")};

specs3(4) = TableColSpec;
specs3(4).Span = 1;
specs3(4).Style = {Width("12%")};

specs3(5) = TableColSpec;
specs3(5).Span = 1;
specs3(5).Style = {Width("6%")};

specs3(6) = TableColSpec;
specs3(6).Span = 1;
specs3(6).Style = {Width("12%")};

specs3(7) = TableColSpec;
specs3(7).Span = 1;
specs3(7).Style = {Width("6%")};

specs3(8) = TableColSpec;
specs3(8).Span = 1;
specs3(8).Style = {Width("12%")};

specs3(9) = TableColSpec;
specs3(9).Span = 1;
specs3(9).Style = {Width("6%")};

specs3(10) = TableColSpec;
specs3(10).Span = 1;
specs3(10).Style = {Width("12%")};

specs3(11) = TableColSpec;
specs3(11).Span = 1;
specs3(11).Style = {Width("6%")};

grps(1).ColSpecs = specs3;
headerContent = ...
    { ...
    ' ', 'method', ['g'], ['Ag|A [Q0]'], ...
        ['B Q0' ], ...
        ['Ag|A [Q1]' ], ...
        ['B Q1' ], ...
        ['Ag|A [Q2]' ], ...
        ['B Q2'], ...
        ['Ag|A [Q3]'], ...
        ['B [Q3]'] ...
    };

bodyContent = ...
    { ...
    '1', 'Imaging (2,3pes)', ...
        [num2str(gaintaballg(1))], ...
        [num2str(coeffsallg(1,2),'%4.3g') ' | ' num2str(coeffsallg(1,2)/coeffsallg(1,1),'%4.3g')], ...
        [num2str(coeffsallg(1,6),'%4.3g')], ...
        [num2str(coeffsallg(1,3),'%4.3g') ' | ' num2str(coeffsallg(1,3)/coeffsallg(1,1),'%4.3g')], ...
        [num2str(coeffsallg(1,7),'%4.3g')], ...
        [num2str(coeffsallg(1,4),'%4.3g') ' | ' num2str(coeffsallg(1,4)/coeffsallg(1,1),'%4.3g')], ...
        [num2str(coeffsallg(1,8),'%4.3g')], ...
        [num2str(coeffsallg(1,5),'%4.3g') ' | ' num2str(coeffsallg(1,5)/coeffsallg(1,1),'%4.3g')], ...
        [num2str(coeffsallg(1,9),'%4.3g')] ...
        ; ...
        '2', '', ...
        [num2str(gaintaballg(2))], ...
        [num2str(coeffsallg(2,2),'%4.3g') ' | '  num2str(coeffsallg(2,2)/coeffsallg(2,1),'%4.3g')], ...
        [num2str(coeffsallg(2,6),'%4.3g')], ...
        [num2str(coeffsallg(2,3),'%4.3g') ' | '  num2str(coeffsallg(2,3)/coeffsallg(2,1),'%4.3g')], ...
        [num2str(coeffsallg(2,7),'%4.3g')], ...
        [num2str(coeffsallg(2,4),'%4.3g') ' | '  num2str(coeffsallg(2,4)/coeffsallg(2,1),'%4.3g')], ...
        [num2str(coeffsallg(2,8),'%4.3g')], ...
        [num2str(coeffsallg(2,5),'%4.3g') ' | '  num2str(coeffsallg(2,5)/coeffsallg(2,1),'%4.3g')], ...
        [num2str(coeffsallg(2,9),'%4.3g')] ...
        ; ...
        '3', '', ...
        ['Mean'], ...
        ['| ' num2str(quaboDETtable(inddetrow,7),'%4.3g')], ...
        [num2str(quaboDETtable(inddetrow,11),'%4.3g')], ...
        ['| ' num2str(quaboDETtable(inddetrow,8),'%4.3g')], ...
        [num2str(quaboDETtable(inddetrow,12),'%4.3g')], ...
        ['| ' num2str(quaboDETtable(inddetrow,9),'%4.3g')], ...
        [num2str(quaboDETtable(inddetrow,13),'%4.3g')], ...
        ['| ' num2str(quaboDETtable(inddetrow,10),'%4.3g')], ...
        [num2str(quaboDETtable(inddetrow,14),'%4.3g')] ...
        ; ...
        '4', 'PH (4,5pes)', ...  
        [num2str(gaintaballg(1))], ...
        [num2str(gaintaballg(1)*AAph(1,1),'%4.3g') ' | '  num2str(AAph(1,1),'%4.3g')], ...
        [num2str(BBph(1,1),'%4.3g')], ...
        [num2str(gaintaballg(1)*AAph(2,1),'%4.3g') ' | '  num2str(AAph(2,1),'%4.3g')], ...
        [num2str(BBph(2,1),'%4.3g')], ...
        [num2str(gaintaballg(1)*AAph(3,1),'%4.3g') ' | '  num2str(AAph(3,1),'%4.3g')], ...
        [num2str(BBph(3,1),'%4.3g')], ...
        [num2str(gaintaballg(1)*AAph(4,1),'%4.3g') ' | '  num2str(AAph(4,1),'%4.3g')], ...
        [num2str(BBph(4,1),'%4.3g')] ...
        ; ...
        '5', '', ...
        [num2str(gaintaballg(2),'%4.3g')], ...
        [num2str(gaintaballg(2)*AAph(1,2),'%4.3g') ' | '  num2str(AAph(1,2),'%4.3g')], ...
        [num2str(BBph(1,2),'%4.3g')], ...
        [num2str(gaintaballg(2)*AAph(2,2)) ' | '  num2str(AAph(2,2),'%4.3g')], ...
        [num2str(BBph(2,2),'%4.3g')], ...
        [num2str(gaintaballg(2)*AAph(3,2)) ' | '  num2str(AAph(3,2),'%4.3g')], ...
        [num2str(BBph(3,2),'%4.3g')], ...
        [num2str(gaintaballg(2)*AAph(4,2)) ' | '  num2str(AAph(4,2),'%4.3g')], ...
        [num2str(BBph(4,2),'%4.3g')] ...
        ; ...
        '6', '', ...
        'Mean', ...
        [' | '  num2str(AAph2(1),'%4.3g')], ...
        [num2str(BBph2(1),'%4.3g')], ...
        [ ' | '  num2str(AAph2(2),'%4.3g')], ...
        [num2str(BBph2(2),'%4.3g')], ...
        [' | '  num2str(AAph2(3),'%4.3g')], ...
        [num2str(BBph2(3),'%4.3g')], ...
        [ ' | '  num2str(AAph2(4),'%4.3g')], ...
        [num2str(BBph2(4),'%4.3g')] ...
        ; ...
        '7', 'PH/Ima (mean coeffs)', ...
        ['any'], ...
        ['| ' num2str(AAimaph(1),'%4.3g')], ...
        [num2str(BBimaph(1),'%4.3g')], ...
        ['| ' num2str(AAimaph(2),'%4.3g')], ...
        [num2str(BBimaph(2),'%4.3g')], ...
        ['| ' num2str(AAimaph(3),'%4.3g')], ...
        [num2str(BBimaph(3),'%4.3g')], ...
        ['| ' num2str(AAimaph(4),'%4.3g')], ...
        [num2str(BBimaph(4),'%4.3g')] ...
        ; ...
        '8', 'Ima/PH (2,5pes)', ...
        [num2str(gaintaballg(1))], ...
        [num2str(gaintaballg(1)*An(1,1),'%4.3g') ' | '  num2str(An(1,1),'%4.3g')], ...
        [num2str(Bn(1,1),'%4.3g')], ...
        [num2str(gaintaballg(1)*An(2,1),'%4.3g') ' | '  num2str(An(2,1),'%4.3g')], ...
        [num2str(Bn(2,1),'%4.3g')], ...
        [num2str(gaintaballg(1)*An(3,1),'%4.3g') ' | '  num2str(An(3,1),'%4.3g')], ...
        [num2str(Bn(3,1),'%4.3g')], ...
        [num2str(gaintaballg(1)*An(4,1),'%4.3g') ' | '  num2str(An(4,1),'%4.3g')], ...
        [num2str(Bn(4,1),'%4.3g')] ...
        ; ...
        '9', '', ...
        [num2str(gaintaballg(2),'%4.3g')], ...
        [num2str(gaintaballg(2)*An(1,2),'%4.3g') ' | '  num2str(An(1,2),'%4.3g')], ...
        [num2str(Bn(1,2),'%4.3g')], ...
        [num2str(gaintaballg(2)*An(2,2),'%4.3g') ' | '  num2str(An(2,2),'%4.3g')], ...
        [num2str(Bn(2,2),'%4.3g')], ...
        [num2str(gaintaballg(2)*An(3,2),'%4.3g') ' | '  num2str(An(3,2),'%4.3g')], ...
        [num2str(Bn(3,2),'%4.3g')], ...
        [num2str(gaintaballg(2)*An(4,2),'%4.3g') ' | '  num2str(An(4,2),'%4.3g')], ...
        [num2str(Bn(4,2),'%4.3g')] ...
        ; ...
        '10', '', ...
        'mean', ...
        ['| ' num2str(An2(1),'%4.3g')], ...
        [num2str(Bn2(1),'%4.3g')], ...
        ['| ' num2str(An2(2),'%4.3g')], ...
        [num2str(Bn2(2),'%4.3g')], ...
        ['| ' num2str(An2(3),'%4.3g')], ...
        [num2str(Bn2(3),'%4.3g')], ...
        ['| ' num2str(An2(4),'%4.3g')], ...
        [num2str(Bn2(4),'%4.3g')] ...
        ; ...
        '11', 'Mean of 7 and 10', ...
        ' any', ...
        ['| ' num2str(Af(1),'%4.3g')], ...
        [num2str(Bf(1),'%4.3g')], ...
        ['| ' num2str(Af(2),'%4.3g')], ...
        [num2str(Bf(2),'%4.3g')], ...
        ['| ' num2str(Af(3),'%4.3g')], ...
        [num2str(Bf(3),'%4.3g')], ...
        ['| ' num2str(Af(4),'%4.3g')], ...
        [num2str(Bf(4),'%4.3g')] ...
    };
tableContent = [headerContent; bodyContent];

table = Table(tableContent);
table.ColSpecGroups = grps;

table.Style = tableStyle;
table.TableEntriesStyle = tableEntriesStyle;

firstRow = table.Children(1);
firstRow.Style = headerRowStyle; 

add(sec5,table);
%     tableDACvsPE2=BaseTable({' ' 'method       .' ['Gain ini'] ['Ag|A Q0'] ...
%         ['B Q0' ] ...
%         ['Ag|A Q1' ] ...
%         ['B Q1' ] ...
%         ['Ag|A Q2' ] ...
%         ['B Q2'] ...
%         ['Ag|A Q3'] ...
%         ['B Q3'] ...
%         ; ...
%         '1' 'Imaging (2,3pes)' ...
%         [num2str(gaintaballg(1))] ...
%         [num2str(coeffsallg(1,2),'%4.3g') ' | ' num2str(coeffsallg(1,2)/coeffsallg(1,1),'%4.3g')] ...
%         [num2str(coeffsallg(1,6),'%4.3g')] ...
%         [num2str(coeffsallg(1,3),'%4.3g') ' | ' num2str(coeffsallg(1,3)/coeffsallg(1,1),'%4.3g')] ...
%         [num2str(coeffsallg(1,7),'%4.3g')] ...
%         [num2str(coeffsallg(1,4),'%4.3g') ' | ' num2str(coeffsallg(1,4)/coeffsallg(1,1),'%4.3g')] ...
%         [num2str(coeffsallg(1,8),'%4.3g')] ...
%         [num2str(coeffsallg(1,5),'%4.3g') ' | ' num2str(coeffsallg(1,5)/coeffsallg(1,1),'%4.3g')] ...
%         [num2str(coeffsallg(1,9),'%4.3g')] ...
%         ; ...
%         '2' '' ...
%         [num2str(gaintaballg(2))] ...
%         [num2str(coeffsallg(2,2),'%4.3g') ' | '  num2str(coeffsallg(2,2)/coeffsallg(2,1),'%4.3g')] ...
%         [num2str(coeffsallg(2,6),'%4.3g')] ...
%         [num2str(coeffsallg(2,3),'%4.3g') ' | '  num2str(coeffsallg(2,3)/coeffsallg(2,1),'%4.3g')] ...
%         [num2str(coeffsallg(2,7),'%4.3g')] ...
%         [num2str(coeffsallg(2,4),'%4.3g') ' | '  num2str(coeffsallg(2,4)/coeffsallg(2,1),'%4.3g')] ...
%         [num2str(coeffsallg(2,8),'%4.3g')] ...
%         [num2str(coeffsallg(2,5),'%4.3g') ' | '  num2str(coeffsallg(2,5)/coeffsallg(2,1),'%4.3g')] ...
%         [num2str(coeffsallg(2,9),'%4.3g')] ...
%         ; ...
%         '3' '' ...
%         ['Mean'] ...
%         ['| ' num2str(quaboDETtable(inddetrow,7),'%4.3g')] ...
%         [num2str(quaboDETtable(inddetrow,11),'%4.3g')] ...
%         ['| ' num2str(quaboDETtable(inddetrow,8),'%4.3g')] ...
%         [num2str(quaboDETtable(inddetrow,12),'%4.3g')] ...
%         ['| ' num2str(quaboDETtable(inddetrow,9),'%4.3g')] ...
%         [num2str(quaboDETtable(inddetrow,13),'%4.3g')] ...
%         ['| ' num2str(quaboDETtable(inddetrow,10),'%4.3g')] ...
%         [num2str(quaboDETtable(inddetrow,14),'%4.3g')] ...
%         ; ...
%         '4' 'PH (4,5pes)' ...  
%         [num2str(gaintaballg(1))] ...
%         [num2str(gaintaballg(1)*AAph(1,1),'%4.3g') ' | '  num2str(AAph(1,1),'%4.3g')] ...
%         [num2str(BBph(1,1),'%4.3g')] ...
%         [num2str(gaintaballg(1)*AAph(2,1),'%4.3g') ' | '  num2str(AAph(2,1),'%4.3g')] ...
%         [num2str(BBph(2,1),'%4.3g')] ...
%         [num2str(gaintaballg(1)*AAph(3,1),'%4.3g') ' | '  num2str(AAph(3,1),'%4.3g')] ...
%         [num2str(BBph(3,1),'%4.3g')] ...
%         [num2str(gaintaballg(1)*AAph(4,1),'%4.3g') ' | '  num2str(AAph(4,1),'%4.3g')] ...
%         [num2str(BBph(4,1),'%4.3g')] ...
%         ; ...
%         '5' '' ...
%         [num2str(gaintaballg(2),'%4.3g')] ...
%         [num2str(gaintaballg(2)*AAph(1,2),'%4.3g') ' | '  num2str(AAph(1,2),'%4.3g')] ...
%         [num2str(BBph(1,2),'%4.3g')] ...
%         [num2str(gaintaballg(2)*AAph(2,2)) ' | '  num2str(AAph(2,2),'%4.3g')] ...
%         [num2str(BBph(2,2),'%4.3g')] ...
%         [num2str(gaintaballg(2)*AAph(3,2)) ' | '  num2str(AAph(3,2),'%4.3g')] ...
%         [num2str(BBph(3,2),'%4.3g')] ...
%         [num2str(gaintaballg(2)*AAph(4,2)) ' | '  num2str(AAph(4,2),'%4.3g')] ...
%         [num2str(BBph(4,2),'%4.3g')] ...
%         ; ...
%         '6' 'PH/Ima (mean A,B coeffs)' ...
%         ['any'] ...
%         ['| ' num2str(AAimaph(1),'%4.3g')] ...
%         [num2str(BBimaph(1),'%4.3g')] ...
%         ['| ' num2str(AAimaph(2),'%4.3g')] ...
%         [num2str(BBimaph(2),'%4.3g')] ...
%         ['| ' num2str(AAimaph(3),'%4.3g')] ...
%         [num2str(BBimaph(3),'%4.3g')] ...
%         ['| ' num2str(AAimaph(4),'%4.3g')] ...
%         [num2str(BBimaph(4),'%4.3g')] ...
%         ; ...
% %         '7) PH/Ima dark (mean A,B coeffs)' ...
% %         [num2str(gaintaballg(2))] ...
% %         [num2str(AAimaph(1,2))] ...
% %         [num2str(BBimaph(1,2))] ...
% %         [num2str(AAimaph(2,2))] ...
% %         [num2str(BBimaph(2,2))] ...
% %         [num2str(AAimaph(3,2))] ...
% %         [num2str(BBimaph(3,2))] ...
% %         [num2str(AAimaph(4,2))] ...
% %         [num2str(BBimaph(4,2))] ...
% %         ; ...
%         '7' 'Ima/PH (2,5pes)' ...
%         [num2str(gaintaballg(1))] ...
%         [num2str(gaintaballg(1)*An(1,1),'%4.3g') ' | '  num2str(An(1,1),'%4.3g')] ...
%         [num2str(Bn(1,1),'%4.3g')] ...
%         [num2str(gaintaballg(1)*An(2,1),'%4.3g') ' | '  num2str(An(2,1),'%4.3g')] ...
%         [num2str(Bn(2,1),'%4.3g')] ...
%         [num2str(gaintaballg(1)*An(3,1),'%4.3g') ' | '  num2str(An(3,1),'%4.3g')] ...
%         [num2str(Bn(3,1),'%4.3g')] ...
%         [num2str(gaintaballg(1)*An(4,1),'%4.3g') ' | '  num2str(An(4,1),'%4.3g')] ...
%         [num2str(Bn(4,1),'%4.3g')] ...
%         ; ...
%         '8' '' ...
%         [num2str(gaintaballg(2),'%4.3g')] ...
%         [num2str(gaintaballg(2)*An(1,2),'%4.3g') ' | '  num2str(An(1,2),'%4.3g')] ...
%         [num2str(Bn(1,2),'%4.3g')] ...
%         [num2str(gaintaballg(2)*An(2,2),'%4.3g') ' | '  num2str(An(2,2),'%4.3g')] ...
%         [num2str(Bn(2,2),'%4.3g')] ...
%         [num2str(gaintaballg(2)*An(3,2),'%4.3g') ' | '  num2str(An(3,2),'%4.3g')] ...
%         [num2str(Bn(3,2),'%4.3g')] ...
%         [num2str(gaintaballg(2)*An(4,2),'%4.3g') ' | '  num2str(An(4,2),'%4.3g')] ...
%         [num2str(Bn(4,2),'%4.3g')] ...
%         ; ...
%         '9' 'mean' ...
%         ' any' ...
%         ['| ' num2str(An2(1),'%4.3g')] ...
%         [num2str(Bn2(1),'%4.3g')] ...
%         ['| ' num2str(An2(2),'%4.3g')] ...
%         [num2str(Bn2(2),'%4.3g')] ...
%         ['| ' num2str(An2(3),'%4.3g')] ...
%         [num2str(Bn2(3),'%4.3g')] ...
%         ['| ' num2str(An2(4),'%4.3g')] ...
%         [num2str(Bn2(4),'%4.3g')] ...
%         ; ...
%         '10' 'Mean of 7 and 9' ...
%         ' any' ...
%         ['| ' num2str(Af(1),'%4.3g')] ...
%         [num2str(Bf(1),'%4.3g')] ...
%         ['| ' num2str(Af(2),'%4.3g')] ...
%         [num2str(Bf(2),'%4.3g')] ...
%         ['| ' num2str(Af(3),'%4.3g')] ...
%         [num2str(Bf(3),'%4.3g')] ...
%         ['| ' num2str(Af(4),'%4.3g')] ...
%         [num2str(Bf(4),'%4.3g')] ...
%         });
%     add(sec5,tableDACvsPE2);
    
end

%% CPS vs DAC
%% recalculate coeffs
%% redo with 2 methods:
%% 1) use 2 and 5 pe levels and curves
%ima: pestepImacps,  dac2=pestepImadac(quad,ig,1); %start at 2pe
%ph: pestepphcps(iquad,gainkk,ida) % starts 4pe
% cps = 10^(E dac + F)
% cps2=10^(E dac2 + F) and  cps5=10^(E dac5 + F)
% soit E = (dac5 - dac2) / log10(cps5/cps2)
% et F = log10(cps2) - dac2* E;
if makereport==1
    sec6 = Section;
    sec6.Title = ['CPS vs PE relationship'];
end
EE=zeros(4, numel(gaintaballg));
FF=zeros(4, numel(gaintaballg));
for quad=1:4
    for ig=1: numel(gaintaballg)
        dac2=pestepImadac(quad,ig,1); %start at 2pe
        cps2=pestepImacps(quad,ig,1);
        dac5=pestepPHdac(quad,ig,2); %start at 4pe
        cps5=pestepphcps(quad,ig,2);
        EE(quad,ig) =    log10(cps5/cps2)/(dac5 - dac2) ;
        FF(quad,ig) =  log10(cps2) - dac2* EE(quad,ig);
    end
end



%% 2) use mean of E_ima F_ph and E_ima F_ph
%CPS fit Coeffs E,F in 10^{(E DAC + F)} at gain ini
%ima: cpsfitA cpsfitB
% cpsfitA(jj,ii,igg)=countfit.p1;
%ph: cpsfitH(iquad,gainkk)=countfit.p1;
%ph: cpsfitI(iquad,gainkk)=countfit.p2;
%% update mixed figure
EE2=zeros(4, numel(gaintaballg));
FF2=zeros(4, numel(gaintaballg));
Ef=zeros(4, numel(gaintaballg));
Ff=zeros(4, numel(gaintaballg));
Jf=zeros(4, numel(gaintaballg));
Kf=zeros(4, numel(gaintaballg));
for quad=1:4
    for ig=1: numel(gaintaballg)
        dac2=pestepImadac(quad,ig,1); %start at 2pe
        cps2=pestepImacps(quad,ig,1);
        dac5=pestepPHdac(quad,ig,2); %start at 4pe
        cps5=pestepphcps(quad,ig,2);
        % Q0:[1:8 9:16] Q1: [1:8 1:8]  Q2: [9:16 1:8] Q3: [9:16,9:16]
        
        %%argh x & y inverted in calib_ima for cpsfitA and cpsfitB
        if quad==3
            cpsfitAquad=cpsfitA(1:8, 9:16,ig);
            cpsfitBquad=cpsfitB(1:8, 9:16,ig);
        elseif quad==4
            cpsfitAquad=cpsfitA(1:8, 1:8,ig);
            cpsfitBquad=cpsfitB(1:8, 1:8,ig);
        elseif quad==1
            cpsfitAquad=cpsfitA( 9:16, 1:8,ig);
            cpsfitBquad=cpsfitB( 9:16, 1:8,ig);
        elseif quad==2
            cpsfitAquad=cpsfitA(9:16, 9:16,ig);
            cpsfitBquad=cpsfitB(9:16, 9:16,ig);
        end
        
        EE2(quad,ig) =   mean([median(cpsfitAquad,'all') cpsfitH(quad,ig)]);
        FF2(quad,ig) =  mean([median(cpsfitBquad,'all') cpsfitI(quad,ig)]);
        
        Ef(quad,ig) =   mean([EE(quad,ig) EE2(quad,ig)]);
        Ff(quad,ig) =  mean([FF(quad,ig) FF2(quad,ig)]);
        
        Jf(quad,ig) = gaintaballg(ig) * Ef(quad,ig) * Af(quad);
        Kf(quad,ig) = Ef(quad,ig) * Bf(quad) +  Ff(quad,ig);
    end
end
Jf2=mean(Jf,2);
Kf2=mean(Kf,2);
Ef2=mean(Ef,2);
Ff2=mean(Ff,2);

cpsfitAquad=zeros(4,numel(gaintaballg));
cpsfitBquad=zeros(4,numel(gaintaballg));
for ig=1:numel(gaintaballg)
    disp('****** coeffs E, F (cps = E dac + F) *************')
    disp(['from fit on Ima (~2-4pe):' 'G=' num2str(gaintaballg(ig))])
    
     %%argh x & y inverted in calib_ima for cpsfitA and cpsfitB
    cpsfitAquad(3,ig)=median(cpsfitA(1:8, 9:16,ig),[1 2]);
    cpsfitAquad(4,ig)=median(cpsfitA(1:8,1:8,ig),[1 2]);
    cpsfitAquad(1,ig)=median(cpsfitA( 9:16,1:8,ig),[1 2]);
    cpsfitAquad(2,ig)=median(cpsfitA(9:16, 9:16,ig),[1 2]);
    cpsfitBquad(3,ig)=median(cpsfitB(1:8, 9:16,ig),[1 2]);
    cpsfitBquad(4,ig)=median(cpsfitB(1:8,1:8,ig),[1 2]);
    cpsfitBquad(1,ig)=median(cpsfitB( 9:16,1:8,ig),[1 2]);
    cpsfitBquad(2,ig)=median(cpsfitB(9:16, 9:16,ig),[1 2]);
    disp(['E3:' num2str(median(cpsfitA(1:8, 9:16,ig),[1 2])) ...
        ' E4:' num2str(median(cpsfitA(1:8,1:8,ig),[1 2])) ...
        ' E1:' num2str(median(cpsfitA( 9:16,1:8,ig),[1 2])) ...
        ' E2:' num2str(median(cpsfitA(9:16, 9:16,ig),[1 2]))])
    disp(['from  use of 2 and 5 pe levels and cps curves:'  'G=' num2str(gaintaballg(ig))])
    disp([' E0:' num2str(EE(1,ig)) ...
        ' E1:' num2str(EE(2,ig)) ...
        ' E2:' num2str(EE(3,ig)) ...
        ' E3:' num2str(EE(4,ig))])
    disp(['from  mean of E_ima F_ph and E_ima F_ph:'  'G=' num2str(gaintaballg(ig))])
    disp([' E0' num2str(EE2(1,ig)) ...
        ' E1:' num2str(EE2(2,ig)) ...
        ' E2:' num2str(EE2(3,ig)) ...
        ' E3:' num2str(EE2(4,ig))])
    disp(['final E:'  'G=' num2str(gaintaballg(ig))])
    disp([' E0' num2str(Ef(1,ig)) ...
        ' E1:' num2str(Ef(2,ig)) ...
        ' E2:' num2str(Ef(3,ig)) ...
        ' E3:' num2str(Ef(4,ig))])
    disp(['final J:'  'G=' num2str(gaintaballg(ig))])
    disp([' J0:' num2str(Jf(1,ig)) ...
        ' J1:' num2str(Jf(2,ig)) ...
        ' J2:' num2str(Jf(3,ig)) ...
        ' J3:' num2str(Jf(4,ig))])
    disp(['from fit on Ima (~2-4pe):' 'G=' num2str(gaintaballg(ig))])
    disp(['F2:' num2str(median(cpsfitB(1:8, 9:16,ig),[1 2])) ...
        ' F3:' num2str(median(cpsfitB(1:8,1:8,ig),[1 2])) ...
        ' F0:' num2str(median(cpsfitB( 9:16,1:8,ig),[1 2])) ...
        ' F1:' num2str(median(cpsfitB(9:16, 9:16,ig),[1 2]))])
    disp(['from  use of 2 and 5 pe levels and cps curves:'  'G=' num2str(gaintaballg(ig))])
    disp([' F0:' num2str(FF(1,ig)) ...
        ' F1:' num2str(FF(2,ig)) ...
        ' F2:' num2str(FF(3,ig)) ...
        ' F3:' num2str(FF(4,ig))])
    disp(['from  mean of E_ima F_ph and E_ima F_ph:'  'G=' num2str(gaintaballg(ig))])
    disp([' F0:' num2str(FF2(1,ig)) ...
        ' F1:' num2str(FF2(2,ig)) ...
        ' F2:' num2str(FF2(3,ig)) ...
        ' F3:' num2str(FF2(4,ig))])
    disp(['final F:'  'G=' num2str(gaintaballg(ig))])
    disp([' F0:' num2str(Ff(1,ig)) ...
        ' F1:' num2str(Ff(2,ig)) ...
        ' F2:' num2str(Ff(3,ig)) ...
        ' F3:' num2str(Ff(4,ig))])
    disp(['final K:'  'G=' num2str(gaintaballg(ig))])
    disp([' K0:' num2str(Kf(1,ig)) ...
        ' K1:' num2str(Kf(2,ig)) ...
        ' K2:' num2str(Kf(3,ig)) ...
        ' K3:' num2str(Kf(4,ig))])
    
end
save('tmp2.mat')

if makereport==1
    sec60 = Section;
  %  sec60.Title = ['CPS = 10^( E g DAC + F) = 10^(J pe# + K)'];
  add(sec6,Paragraph(['The CPS vs PE relationship is characterized by it linear form with J and K coefficients such that  ']));
    add(sec6,Paragraph(['CPS  = 10^(J pe# + K)']));
    add(sec6,Paragraph(['We used darks to first deduce the CPS vs DAC relationship (E, F coefficients) by sweeping the threshold such that ']));
    add(sec6,Paragraph(['CPS  = 10^( E DAC + F)']));
    add(sec6,Paragraph(['Coefficients J and K are deduced from the A,B,E and F coeffs and initial gain g :']));
    add(sec6,Paragraph(['J = E A g']));
     add(sec6,Paragraph(['and']));
      add(sec6,Paragraph(['K = E B + F']));
           add(sec6,Paragraph(['The following table gives E, F, J, K coefficients for Quadrants#0,1,2,3.']));
   tableStyle = ...
    { ...
    Width("100%"), ...
    Border("solid"), ...
    RowSep("solid"), ...
    ColSep("solid") ...
    };

tableEntriesStyle = ...
    { ...
    HAlign("center"), ...
    VAlign("middle") ...
    };

headerRowStyle = ...
    { ...
    InnerMargin("2pt","2pt","2pt","2pt"), ...
    BackgroundColor("gray"), ...
    Bold(true) ...
    };
grps(1) = TableColSpecGroup;
grps(1).Span = 11;

specs4(1) = TableColSpec;
specs4(1).Span = 1;
specs4(1).Style = {Width("3%")};

specs4(2) = TableColSpec;
specs4(2).Span = 1;
specs4(2).Style = {Width("15%")};

specs4(3) = TableColSpec;
specs4(3).Span = 1;
specs4(3).Style = {Width("9%")};

specs4(4) = TableColSpec;
specs4(4).Span = 1;
specs4(4).Style = {Width("10%")};

specs4(5) = TableColSpec;
specs4(5).Span = 1;
specs4(5).Style = {Width("8%")};

specs4(6) = TableColSpec;
specs4(6).Span = 1;
specs4(6).Style = {Width("10%")};

specs4(7) = TableColSpec;
specs4(7).Span = 1;
specs4(7).Style = {Width("8%")};

specs4(8) = TableColSpec;
specs4(8).Span = 1;
specs4(8).Style = {Width("10%")};

specs4(9) = TableColSpec;
specs4(9).Span = 1;
specs4(9).Style = {Width("8%")};

specs4(10) = TableColSpec;
specs4(10).Span = 1;
specs4(10).Style = {Width("10%")};

specs4(11) = TableColSpec;
specs4(11).Span = 1;
specs4(11).Style = {Width("8%")};

grps(1).ColSpecs = specs4;
headerContent = ...
    { ...
   '#', 'method', ['g'], ['E|J [Q0]'], ...
        ['F|K [Q0]' ], ...
        ['E|J [Q1]' ], ...
        ['F|K [Q1]' ], ...
        ['E|J [Q2]' ], ...
        ['F|K [Q2]'], ...
        ['E|J [Q3]'], ...
        ['F|K [Q3]'] ...
    };

bodyContent = ...
    { ...
    '1', 'Imaging (2,3pes)', ...
        [num2str(gaintaballg(1))], ...
        [num2str(cpsfitAquad(1,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(1) * cpsfitAquad(1,1),'%4.3g')], ...
        [num2str(cpsfitBquad(1,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(1) * cpsfitAquad(1,1)* Bf(1) + cpsfitBquad(1,1),'%4.3g')], ...
        [num2str(cpsfitAquad(2,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(2) * cpsfitAquad(2,1),'%4.3g')], ...
        [num2str(cpsfitBquad(2,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(2) * cpsfitAquad(2,1)* Bf(2) + cpsfitBquad(2,1),'%4.3g')], ...
        [num2str(cpsfitAquad(3,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(3) * cpsfitAquad(3,1),'%4.3g')], ...
        [num2str(cpsfitBquad(3,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(3) * cpsfitAquad(3,1)* Bf(3) + cpsfitBquad(3,1),'%4.3g')], ...
        [num2str(cpsfitAquad(4,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(4) * cpsfitAquad(4,1),'%4.3g')], ...
        [num2str(cpsfitBquad(4,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(4) * cpsfitAquad(4,1)* Bf(4) + cpsfitBquad(4,1),'%4.3g')] ...
        ; ...
        '2', '', ...
        [num2str(gaintaballg(2))], ...
        [num2str(cpsfitAquad(1,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(1) * cpsfitAquad(1,2),'%4.3g')], ...
        [num2str(cpsfitBquad(1,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(1) * cpsfitAquad(1,2)* Bf(1) + cpsfitBquad(1,2),'%4.3g')], ...
        [num2str(cpsfitAquad(2,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(2) * cpsfitAquad(2,2),'%4.3g')], ...
        [num2str(cpsfitBquad(2,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(2) * cpsfitAquad(2,2)* Bf(2) + cpsfitBquad(2,2),'%4.3g')], ...
        [num2str(cpsfitAquad(3,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(3) * cpsfitAquad(3,2),'%4.3g')], ...
        [num2str(cpsfitBquad(3,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(3) * cpsfitAquad(3,2)* Bf(3) + cpsfitBquad(3,2),'%4.3g')], ...
        [num2str(cpsfitAquad(4,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(4) * cpsfitAquad(4,2),'%4.3g')], ...
        [num2str(cpsfitBquad(4,1),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(4) * cpsfitAquad(4,2)* Bf(4) + cpsfitBquad(4,2),'%4.3g')] ...
        ; ...
        '3', 'PH (4,5pes)', ...
        [num2str(gaintaballg(1))] ...
        [num2str(cpsfitH(1,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(1) * cpsfitH(1,1),'%4.3g')], ...
        [num2str(cpsfitI(1,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(1) * cpsfitH(1,1)* Bf(1) + cpsfitI(1,1),'%4.3g')], ...
        [num2str(cpsfitH(2,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(2) * cpsfitH(2,1),'%4.3g')], ...
        [num2str(cpsfitI(2,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(2) * cpsfitH(2,1)* Bf(2) + cpsfitI(2,1),'%4.3g')], ...
        [num2str(cpsfitH(3,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(3) * cpsfitH(3,1),'%4.3g')], ...
        [num2str(cpsfitI(3,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(3) * cpsfitH(3,1)* Bf(3) + cpsfitI(3,1),'%4.3g')], ...
        [num2str(cpsfitH(4,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(4) * cpsfitH(4,1),'%4.3g')], ...
        [num2str(cpsfitI(4,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(4) * cpsfitH(4,1)* Bf(4) + cpsfitI(4,1),'%4.3g')] ...
        ; ...
        '4', ' ', ...
        [num2str(gaintaballg(2))], ...
        [num2str(cpsfitH(1,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(1) * cpsfitH(1,2),'%4.3g')], ...
        [num2str(cpsfitI(1,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(1) * cpsfitH(1,2)* Bf(1) + cpsfitI(1,2),'%4.3g')], ...
        [num2str(cpsfitH(2,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(2) * cpsfitH(2,2),'%4.3g')], ...
        [num2str(cpsfitI(2,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(2) * cpsfitH(2,2)* Bf(2) + cpsfitI(2,2),'%4.3g')], ...
        [num2str(cpsfitH(3,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(3) * cpsfitH(3,2),'%4.3g')], ...
        [num2str(cpsfitI(3,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(3) * cpsfitH(3,2)* Bf(3) + cpsfitI(3,1),'%4.3g')], ...
        [num2str(cpsfitH(4,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(4) * cpsfitH(4,2),'%4.3g')], ...
        [num2str(cpsfitI(4,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(4) * cpsfitH(4,2)* Bf(4) + cpsfitI(4,1),'%4.3g')] ...
        ; ...
        '5', 'PH/Ima (mean coeffs)', ...
        [num2str(gaintaballg(1))], ...
        [num2str(EE2(1,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(1) * EE2(1,1),'%4.3g')], ...
        [num2str(FF2(1,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(1) * EE2(1,1)* Bf(1) + FF2(1,1),'%4.3g')], ...
        [num2str(EE2(2,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(2) * EE2(2,1),'%4.3g')], ...
        [num2str(FF2(2,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(2) * EE2(2,1)* Bf(2) + FF2(2,1),'%4.3g')], ...
        [num2str(EE2(3,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(3) * EE2(3,1),'%4.3g')], ...
        [num2str(FF2(3,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(3) * EE2(3,1)* Bf(3) + FF2(3,1),'%4.3g')], ...
        [num2str(EE2(4,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(4) * EE2(4,1),'%4.3g')], ...
        [num2str(FF2(4,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(4) * EE2(4,1)* Bf(4) + FF2(4,1),'%4.3g')] ...
        ; ...
        '6', ' ', ...
        [num2str(gaintaballg(2))], ...
        [num2str(EE2(1,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(1) * EE2(1,2),'%4.3g')], ...
        [num2str(FF2(1,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(1) * EE2(1,2)* Bf(1) + FF2(1,2),'%4.3g')], ...
        [num2str(EE2(2,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(2) * EE2(2,2),'%4.3g')], ...
        [num2str(FF2(2,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(2) * EE2(2,2)* Bf(2) + FF2(2,2),'%4.3g')], ...
        [num2str(EE2(3,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(3) * EE2(3,2),'%4.3g')], ...
        [num2str(FF2(3,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(3) * EE2(3,2)* Bf(3) + FF2(3,2),'%4.3g')], ...
        [num2str(EE2(4,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(4) * EE2(4,2),'%4.3g')], ...
        [num2str(FF2(4,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(4) * EE2(4,2)* Bf(4) + FF2(4,2),'%4.3g')] ...
        ; ...
        '7', 'Ima/PH dark (2,5pes)', ...
        [num2str(gaintaballg(1))], ...
        [num2str(EE(1,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(1) * EE(1,1),'%4.3g')], ...
        [num2str(FF(1,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(1) * EE(1,1)* Bf(1) + FF(1,1),'%4.3g')], ...
        [num2str(EE(2,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(2) * EE(2,1),'%4.3g')], ...
        [num2str(FF(2,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(2) * EE(2,1)* Bf(2) + FF(2,1),'%4.3g')], ...
        [num2str(EE(3,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(3) * EE(3,1),'%4.3g')], ...
        [num2str(FF(3,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(3) * EE(3,1)* Bf(3) + FF(3,1),'%4.3g')], ...
        [num2str(EE(4,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(4) * EE(4,1),'%4.3g')], ...
        [num2str(FF(4,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(4) * EE(4,1)* Bf(4) + FF(4,1),'%4.3g')] ...
        ; ...
        '8', '', ...
        [num2str(gaintaballg(2))], ...
        [num2str(EE(1,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(1) * EE(1,2),'%4.3g')], ...
        [num2str(FF(1,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(1) * EE(1,2)* Bf(1) + FF(1,2),'%4.3g')], ...
        [num2str(EE(2,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(2) * EE(2,2),'%4.3g')], ...
        [num2str(FF(2,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(2) * EE(2,2)* Bf(2) + FF(2,2),'%4.3g')], ...
        [num2str(EE(3,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(3) * EE(3,2),'%4.3g')], ...
        [num2str(FF(3,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(3) * EE(3,2)* Bf(3) + FF(3,2),'%4.3g')], ...
        [num2str(EE(4,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(4) * EE(4,2),'%4.3g')], ...
        [num2str(FF(4,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(4) * EE(4,2)* Bf(4) + FF(4,2),'%4.3g')] ...
        ; ...
        '9', 'Mean of 5,6,7 and 8', ...
        [num2str(gaintaballg(1))], ...
        [num2str(Ef(1,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(1) * Ef(1,1),'%4.3g')], ...
        [num2str(Ff(1,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(1) * Ef(1,1)* Bf(1) + Ff(1,1),'%4.3g')], ...
        [num2str(Ef(2,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(2) * Ef(2,1),'%4.3g')], ...
        [num2str(Ff(2,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(2) * Ef(2,1)* Bf(2) + Ff(2,1),'%4.3g')], ...
        [num2str(Ef(3,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(3) * Ef(3,1),'%4.3g')], ...
        [num2str(Ff(3,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(3) * Ef(3,1)* Bf(3) + Ff(3,1),'%4.3g')], ...
        [num2str(Ef(4,1),'%4.3g') ' | ' num2str(gaintaballg(1) *  Af(4) * Ef(4,1),'%4.3g')], ...
        [num2str(Ff(4,1),'%4.3g') ' | ' num2str( gaintaballg(1) *  Af(4) * Ef(4,1)* Bf(4) + Ff(4,1),'%4.3g')] ...
          ; ...
        '10', '', ...
        [num2str(gaintaballg(2))], ...
        [num2str(Ef(1,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(1) * Ef(1,2),'%4.3g')], ...
        [num2str(Ff(1,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(1) * Ef(1,2)* Bf(1) + Ff(1,2),'%4.3g')], ...
        [num2str(Ef(2,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(2) * Ef(2,2),'%4.3g')], ...
        [num2str(Ff(2,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(2) * Ef(2,2)* Bf(2) + Ff(2,2),'%4.3g')], ...
        [num2str(Ef(3,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(3) * Ef(3,2),'%4.3g')], ...
        [num2str(Ff(3,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(3) * Ef(3,2)* Bf(3) + Ff(3,2),'%4.3g')], ...
        [num2str(Ef(4,2),'%4.3g') ' | ' num2str(gaintaballg(2) *  Af(4) * Ef(4,2),'%4.3g')], ...
        [num2str(Ff(4,2),'%4.3g') ' | ' num2str( gaintaballg(2) *  Af(4) * Ef(4,2)* Bf(4) + Ff(4,2),'%4.3g')] ...
          ; ...
        '11', '', ...
        ' any', ...
        [' | ' num2str(Jf2(1),'%4.3g')], ...
        [ ' | ' num2str(Kf2(1),'%4.3g')], ...
        [ ' | ' num2str(Jf2(2),'%4.3g')], ...
        [ ' | ' num2str(Kf2(2),'%4.3g')], ...
        [ ' | ' num2str(Jf2(3),'%4.3g')], ...
        [ ' | ' num2str(Kf2(3),'%4.3g')], ...
        [ ' | ' num2str(Jf2(4),'%4.3g')], ...
        [ ' | ' num2str(Kf2(4),'%4.3g')] ...
       };
tableContent = [headerContent; bodyContent];

table = Table(tableContent);
table.ColSpecGroups = grps;

table.Style = tableStyle;
table.TableEntriesStyle = tableEntriesStyle;

firstRow = table.Children(1);
firstRow.Style = headerRowStyle; 

add(sec6,table);
    
%     tableCPSvsDAC2=BaseTable({'#' 'method' ['Gain ini'] ['E|J [Q0]'] ...
%         ['F|K [Q0]' ] ...
%         ['E|J [Q1]' ] ...
%         ['F|K [Q1]' ] ...
%         ['E|J [Q2]' ] ...
%         ['F|K [Q2]'] ...
%         ['E|J [Q3]'] ...
%         ['F|K [Q3]'] ...
%         ; ...
%         
%     add(sec6,tableCPSvsDAC2);
  
   
    % add(sec6,sec60);
%      sec61 = Section;
%     sec61.Title = ['CPS = 10^( J pe# + K) '];
%     tableCPSvsDAC2=BaseTable({'method' ['Gain ini'] ['J0'] ...
%         ['K0' ] ...
%         ['J1' ] ...
%         ['K1' ] ...
%         ['J2' ] ...
%         ['K2'] ...
%         ['J3'] ...
%         ['K3'] ...
%         ; ...
%         'from 9) A,B' ...
%         [num2str(gaintaballg(1))] ...
%         [num2str(Jf(1,1))] ...
%         [num2str(Kf(1,1))] ...
%         [num2str(Jf(2,1))] ...
%         [num2str(Kf(2,1))] ...
%         [num2str(Jf(3,1))] ...
%         [num2str(Kf(3,1))] ...
%         [num2str(Jf(4,1))] ...
%         [num2str(Kf(4,1))] ...
%            ; ...
%         'from 9) A,B' ...
%         [num2str(gaintaballg(2))] ...
%         [num2str(Jf(1,2))] ...
%         [num2str(Kf(1,2))] ...
%         [num2str(Jf(2,2))] ...
%         [num2str(Kf(2,2))] ...
%         [num2str(Jf(3,2))] ...
%         [num2str(Kf(3,2))] ...
%         [num2str(Jf(4,2))] ...
%         [num2str(Kf(4,2))] ...
%         });
%     add(sec61,tableCPSvsDAC2);
%     add(sec6,sec61);
end



%%MAKE FINAL CPS + PE STEPS FIG
for ig=1:numel(gaintaballg)
    
    %open main Ima fig with 4 quads
    filenmpng=cell2mat(cpsfinalfigcell(ig));
    filenm=[filenmpng(1:end-3) 'fig'];
    imacpsfig=openfig(filenm);
    quadaxes=imacpsfig.Children;
    h= findobj(gcf,'type','axes');
    imah= findobj(h,'type','Line');
    for qq=4:-1:1
        %create
        cpsfig=figure('Name',['Q' num2str(qq-1)],'Position',[100 100 1200 800])
        axetocopy=h(5-qq);
        set(axetocopy,'Units' ,'Normalized')
        set(axetocopy,'OuterPosition' ,[0.1, 0.1, 0.9, 0.9]);
        s = copyobj(axetocopy,cpsfig);
        %cpsfig.Children=quadaxes(qq)
        %%add PH counting curve
        %PHcpsfinalfigcell(qq,ig)
        phfilenmpng=cell2mat(PHcpsfinalfigcell(qq,ig));
        filenm=[phfilenmpng(1:end-3) 'fig'];
        figph=openfig(filenm);
        phh= findobj(gca,'type','Line');
        figure(cpsfig)
        ha= findobj(gcf,'type','axes');
        s2 = copyobj(phh,ha);
        %%add pe levels
        hold on
        %%add pe levels from Ima
        yl=ylim;fs=10;
        p0=plot([pestepImadac(qq,ig,1) pestepImadac(qq,ig,1)] , yl,'k--');
        text(1+pestepImadac(qq,ig,1),0.95*yl(2),'2pe','FontSize',fs,'Color','k')
        plot([pestepImadac(qq,ig,2) pestepImadac(qq,ig,2)] , yl,'k--');
        text(1+pestepImadac(qq,ig,2),0.95*yl(2),'3pe','FontSize',fs,'Color','k')
        plot([pestepImadac(qq,ig,3) pestepImadac(qq,ig,3)] , yl,'k--')
        text(1+pestepImadac(qq,ig,3),0.95*yl(2),'4pe','FontSize',fs,'Color','k')
        %%add pe levels from PH
        p1=  plot([pestepPHdac(qq,ig,1) pestepPHdac(qq,ig,1)] , yl,'g-.');
        text(1+pestepPHdac(qq,ig,1),0.65*yl(2),'4pe','FontSize',fs,'Color','g')
        plot([pestepPHdac(qq,ig,2) pestepPHdac(qq,ig,2)] , yl,'g-.')
        text(1+pestepPHdac(qq,ig,2),0.65*yl(2),'5pe','FontSize',fs,'Color','g')
        plot([pestepPHdac(qq,ig,3) pestepPHdac(qq,ig,3)] , yl,'g-.')
        text(1+pestepPHdac(qq,ig,3),0.65*yl(2),'6pe','FontSize',fs,'Color','g')
        %%add pe levels from An/Bn
        %%%deduce dac of pe levels:
        pelevels=1:6;
        dacn=An2(qq)*gaintaballg(ig)*pelevels + Bn2(qq);
        for pes=1:numel(pelevels)
            p2=plot([dacn(pes) dacn(pes)] , yl,'r--');
            text(1+dacn(pes),0.3*yl(2),[num2str(pes) 'pe'],'FontSize',fs,'Color','r')
        end
        %%add pe levels from Aa2/B
        dacnn=AAimaph(qq)*gaintaballg(ig)*pelevels + BBimaph(qq);
        for pes=1:numel(pelevels)
            p3=plot([dacnn(pes) dacnn(pes)] , yl,'m--');
            text(1+dacnn(pes),0.18*yl(2),[num2str(pes) 'pe'],'FontSize',fs,'Color','m')
        end
        %%add pe levels from final
        dacf=Af(qq)*gaintaballg(ig)*pelevels + Bf(qq);
        for pes=1:numel(pelevels)
            p4=plot([dacf(pes) dacf(pes)] , yl,'b--');
            text(1+dacf(pes),0.1*yl(2),[num2str(pes) 'pe'],'FontSize',fs,'Color','b')
        end
        hold off
        title(['Quad' num2str(qq-1) ', Gain ini:' num2str(gaintaballg(ig))  ', Darks.'])
        legend(gca,[imah(end) phh(end) p0 p1 p2 p3 p4],'cps Imaging','cps PH mode', ...
            'pe steps from Imaging','pe steps from PH', ...
            'pe steps Ima/PH (2 & 5pe)','pe steps from mean A & B coeffs Ima/PH', ...
            'pe steps final','Location','SouthWest','color','none')
        filenmne=[calibdir 'FinalCPSallpes' 'Q' num2str(qq)  'G' num2str(gaintaballg(ig))  '_' datenow ];
        cpsfinalallpesfigcell(iquad,ig)={[filenmne '.png']};
        saveas(gcf,[filenmne '.png'])
        saveas(gcf,[filenmne '.fig'])
        
        close(figph)
      
        
        %add cps curves in report:
        if makereport==1
        add(sec5,Paragraph(['Deduced Pe step locations in DAC are represented with dashed lines in the following figures  using the previous table of A and B coefficients. The following figure shows pe steps for Quad' num2str(qq-1) ' at initial gain of ' num2str(gaintaballg(ig))  ' for dark acquisitions.']));
        plot1=Image([filenmne '.png']);
        widthch=plot1.Width;
        widthima=str2num(widthch(1:strfind(widthch,'px')-1));
        heightch=plot1.Height;
        heightima=str2num(heightch(1:strfind(heightch,'px')-1));
        plot1.Width='550px';
        plot1.Height=[ num2str(floor(550/widthima*heightima)) 'px'];
        add(sec5,plot1);
        end
    end
      close(imacpsfig)
end

%%MAKE FINAL CPS + cps fit FIG
for ig=1:numel(gaintaballg)
    
    %open main Ima fig with 4 quads
    filenmpng=cell2mat(cpsfinalfigcell(ig));
    filenm=[filenmpng(1:end-3) 'fig'];
    imacpsfig=openfig(filenm);
    quadaxes=imacpsfig.Children;
    h= findobj(gcf,'type','axes');
    imah= findobj(h,'type','Line');
    for qq2=1:4
        %create
        cpsfig=figure('Name',['Q' num2str(4-qq2)],'Position',[100 100 1200 800])
        axetocopy=h(qq2);
        set(axetocopy,'Units' ,'Normalized')
        set(axetocopy,'OuterPosition' ,[0.1, 0.1, 0.9, 0.9]);
        s = copyobj(axetocopy,cpsfig);
        %make the pe step line invisble:
            h2= findobj(cpsfig,'type','axes');
            imah2= findobj(h2,'type','Line');
            linpe=imah2(1);
            set(linpe,'Visible','off')
            linpe2=imah2(2);
            set(linpe2,'Visible','off')
            linpe3=imah2(3);
            set(linpe3,'Visible','off')
        %cpsfig.Children=quadaxes(qq)
        %%add PH counting curve
        %PHcpsfinalfigcell(qq,ig)
        qq=5-qq2;
        phfilenmpng=cell2mat(PHcpsfinalfigcell(qq,ig));
        filenm=[phfilenmpng(1:end-3) 'fig'];
        figph=openfig(filenm);
        phh= findobj(gca,'type','Line');
        figure(cpsfig)
        ha= findobj(gcf,'type','axes');
        s2 = copyobj(phh,ha);
        %%add cps fit
        pelevels=1:6;
        dacfit=Af(qq)*gaintaballg(ig)*pelevels + Bf(qq);
        hold on
        %%add cps fit from Ima
        cpsIma=10.^(cpsfitAquad(qq,ig)*dacfit+cpsfitBquad(qq,ig));
        p0=plot(dacfit,cpsIma,'b:');
        %%add cps fit from PH
        cpsph=10.^(cpsfitH(qq,ig)*dacfit+cpsfitI(qq,ig));
        p0b=plot(dacfit,cpsph,'c:');
        %%add cps fit from 2pe-5pe
        cps25=10.^(EE(qq,ig)*dacfit+FF(qq,ig));
        p1=plot(dacfit,cps25,'m-.');
        %%add cps fit from E,F coeffs
        cpscoe=10.^(EE2(qq,ig)*dacfit+FF2(qq,ig));
        p2=plot(dacfit,cpscoe,'k-.');
        %%add cps fit from final
        cpsf=10.^(Ef(qq,ig)*dacfit+Ff(qq,ig));
        p3=plot(dacfit,cpsf,'r--');
        
        hold off
        legend(gca,[imah(end) phh(end) p0 p0b p1 p2 p3 ],'cps Imaging', 'cps PH','fit from imaging cps','fit from PH cps',...
            'fit from cps at 2 and 5 pe (Imaging/PH)','fit from mean coeffs', ...
            'final','color','none','Location','NorthEast')
         title(['Quad' num2str(qq-1) ', Gain ini:' num2str(gaintaballg(ig))  ', Darks.'])
        filenmne=[calibdir 'FinalCPSallfit' 'Q' num2str(qq)  'G' num2str(gaintaballg(ig)) '_' datenow ];
        cpsfinalallfitfigcell(qq,ig)={[filenmne '.png']};
        saveas(gcf,[filenmne '.png'])
        saveas(gcf,[filenmne '.fig'])
        
       
        close(figph)
    end
     close(imacpsfig)
     
      %add cps curves:
      %for qq=1:4
        if makereport==1
        add(sec6,Paragraph(['The following figure shows the fit of cps curves (giving E, F coeffs) for Quad ' num2str(qq-1) ' at an initial gain of ' num2str(gaintaballg(ig))  ' for dark acquisitions.']));
        plot1=Image([filenmne '.png']);
        
         imgStyle = {ScaleToFit(true)};
            img1 = Image(cell2mat(cpsfinalallfitfigcell(1,ig)));
            img1.Style = imgStyle;
            img2=Image(cell2mat(cpsfinalallfitfigcell(2,ig)));
            img2.Style = imgStyle;
            img3 = Image(cell2mat(cpsfinalallfitfigcell(3,ig)));
            img3.Style = imgStyle;
            img4=Image(cell2mat(cpsfinalallfitfigcell(4,ig)));
            img4.Style = imgStyle;
            %Insert images in the row of a 1x3, invisible layout table (lot).
            
            lot = Table({img1, ' ', img2; img3, ' ', img4});
            %The images will be sized to fit the table entries only if their height and width is specified.
            
            lot.entry(1,1).Style = {Width('3.2in'), Height('2in')};
            lot.entry(1,2).Style = {Width('.2in'), Height('2in')};
            lot.entry(1,3).Style = {Width('3.2in'), Height('2in')};
            lot.entry(2,1).Style = {Width('3.2in'), Height('2in')};
            lot.entry(2,2).Style = {Width('.2in'), Height('2in')};
            lot.entry(2,3).Style = {Width('3.2in'), Height('2in')};
            %Make the table span the width of the page between the margins. Tell the table layout manager to not resize the table columns to fit the images.
            
            lot.Style = {ResizeToFitContents(false), Width('100%')};
            %Generate and display the report.
            
            add(sec6, lot);
      %  end 
%         widthch=plot1.Width;
%         widthima=str2num(widthch(1:strfind(widthch,'px')-1));
%         heightch=plot1.Height;
%         heightima=str2num(heightch(1:strfind(heightch,'px')-1));
%         plot1.Width='600px';
%         plot1.Height=[ num2str(floor(600/widthima*heightima)) 'px'];
%         add(sec6,plot1);
        end
end
if makereport==1
    add(secB,sec5);
    add(rpt,secB);
    add(rpt,sec6);
end

savedata=1;
if savedata==1
    quaboDETtable(inddetrow,7)=Af(1);
    quaboDETtable(inddetrow,8)=Af(2);
    quaboDETtable(inddetrow,9)=Af(3);
    quaboDETtable(inddetrow,10)=Af(4);
    quaboDETtable(inddetrow,11)=Bf(1);
    quaboDETtable(inddetrow,12)=Bf(2);
    quaboDETtable(inddetrow,13)=Bf(3);
    quaboDETtable(inddetrow,14)=Bf(4);
    
    
    save([getuserdir '\panoseti\Calibrations\' 'CalibrationDB.mat'],'quaboDETtable')
end
