function tmp = importfilepcatxt(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TMP = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  TMP = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  tmp = importfile("C:\Users\User\Documents\panoseti\PANOapp\tmp.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Jun-2020 19:15:17

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["VarName1", "bfe5040000000000f882d53200005800670049007a0033001d0022006000ac0"];
opts.VariableTypes = ["double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "bfe5040000000000f882d53200005800670049007a0033001d0022006000ac0", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "bfe5040000000000f882d53200005800670049007a0033001d0022006000ac0", "EmptyFieldRule", "auto");

% Import the data
tmp = readtable(filename, opts);

end