%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\jerome\Documents\panoseti\DATA\temperature\LogFile_0002.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/05/02 17:51:40

%% Initialize variables.
%filename = 'C:\Users\jerome\Documents\panoseti\DATA\temperature\LogFile_0002.txt';
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: datetimes (%{MM/dd/yy HH:mm:ss}D)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%{MM/dd/yy HH:mm:ss}D%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
LogFile = table(dataArray{1:end-1}, 'VariableNames', {'VarName1','Time','TemperatureC'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% LogFile0002.Time=datenum(LogFile0002.Time);

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;